name: Test

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm ci
      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          LINTER_RULES_PATH: /
          FILTER_REGEX_EXCLUDE: (.*dist\/.*)|(.husky\/.*)
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: main
      # - run: npm test
